name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "**"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/python-poetry-env
      - run: poetry run pre-commit run --all-files
